company_name: "Sage & Stone"
established_year: 2025
tagline: "Rooms that remember"

phone_number: "+44 (0) 20 1234 5678"
email: "hello@sageandstone.com"
address: |
  The Old Joinery
  Unit 4
  Herefordshire HR4 9AB
business_hours: |
  Monday - Friday: 9am - 5pm
  Saturday: By appointment
  Sunday: Closed

primary_color: "#1A2F23"
secondary_color: "#4A6350"
accent_color: "#A0563B"
background_color: "#F7F5F1"
text_color: "#1A2F23"
surface_color: "#EDE8E0"
surface_elevated_color: "#FFFFFF"
text_light_color: "#5A6E5F"

heading_font: "Playfair Display"
body_font: "Lato"

instagram_url: "https://instagram.com/sageandstone"
facebook_url: ""
linkedin_url: ""
twitter_url: ""
youtube_url: ""
tiktok_url: ""

gtm_container_id: ""
ga_measurement_id: ""

cookie_banner_enabled: false
