# Generated by Django 5.2.9 on 2025-12-12 17:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterNavigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Short tagline displayed in the footer (max 255 characters).",
                        max_length=255,
                    ),
                ),
                (
                    "link_sections",
                    wagtail.fields.StreamField(
                        [("section", 11)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Section title (max 50 characters).",
                                    "max_length": 50,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("url", "External URL"),
                                        ("email", "Email"),
                                        ("phone", "Phone"),
                                        ("anchor", "Anchor"),
                                    ],
                                    "help_text": "Select the type of link.",
                                },
                            ),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Select an internal page.",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Enter an external URL (include https://).",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {
                                    "help_text": "Enter an email address.",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Custom display text for the link (optional).",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": None,
                                    "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 1),
                                        ("page", 2),
                                        ("url", 3),
                                        ("email", 4),
                                        ("phone", 5),
                                        ("anchor", 6),
                                        ("link_text", 7),
                                        ("open_in_new_tab", 8),
                                    ]
                                ],
                                {},
                            ),
                            10: (
                                "wagtail.blocks.ListBlock",
                                (9,),
                                {
                                    "help_text": "Links in this section (max 10 links).",
                                    "max_num": 10,
                                    "required": True,
                                },
                            ),
                            11: (
                                "wagtail.blocks.StructBlock",
                                [[("title", 0), ("links", 10)]],
                                {},
                            ),
                        },
                        help_text="Footer link sections (min 2, max 4 sections).",
                    ),
                ),
                (
                    "auto_service_areas",
                    models.BooleanField(
                        default=False,
                        help_text="Automatically populate service areas section (logic TBD).",
                    ),
                ),
                (
                    "social_facebook",
                    models.URLField(
                        blank=True, default="", help_text="Facebook page URL."
                    ),
                ),
                (
                    "social_instagram",
                    models.URLField(
                        blank=True, default="", help_text="Instagram profile URL."
                    ),
                ),
                (
                    "social_linkedin",
                    models.URLField(
                        blank=True, default="", help_text="LinkedIn page URL."
                    ),
                ),
                (
                    "social_youtube",
                    models.URLField(
                        blank=True, default="", help_text="YouTube channel URL."
                    ),
                ),
                (
                    "social_x",
                    models.URLField(
                        blank=True, default="", help_text="X (Twitter) profile URL."
                    ),
                ),
                (
                    "copyright_text",
                    models.CharField(
                        blank=True,
                        default="© {year} {company_name}. All rights reserved.",
                        help_text="Copyright text. Use {year} and {company_name} as placeholders (max 255 characters).",
                        max_length=255,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Footer Navigation",
            },
        ),
        migrations.CreateModel(
            name="HeaderNavigation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_items",
                    wagtail.fields.StreamField(
                        [("item", 12)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Menu item label (max 50 characters).",
                                    "max_length": 50,
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("url", "External URL"),
                                        ("email", "Email"),
                                        ("phone", "Phone"),
                                        ("anchor", "Anchor"),
                                    ],
                                    "help_text": "Select the type of link.",
                                },
                            ),
                            2: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Select an internal page.",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Enter an external URL (include https://).",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {
                                    "help_text": "Enter an email address.",
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Custom display text for the link (optional).",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": None,
                                    "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 1),
                                        ("page", 2),
                                        ("url", 3),
                                        ("email", 4),
                                        ("phone", 5),
                                        ("anchor", 6),
                                        ("link_text", 7),
                                        ("open_in_new_tab", 8),
                                    ]
                                ],
                                {
                                    "help_text": "Link destination for this menu item.",
                                    "required": True,
                                },
                            ),
                            10: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("link", 9)]],
                                {},
                            ),
                            11: (
                                "wagtail.blocks.ListBlock",
                                (10,),
                                {
                                    "help_text": "Submenu items (optional, max 8 items).",
                                    "max_num": 8,
                                    "required": False,
                                },
                            ),
                            12: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 0), ("link", 9), ("children", 11)]],
                                {},
                            ),
                        },
                        help_text="Top-level menu items (max 8).",
                    ),
                ),
                (
                    "show_phone_in_header",
                    models.BooleanField(
                        default=True, help_text="Display phone number in the header."
                    ),
                ),
                (
                    "header_cta_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable the header CTA button."
                    ),
                ),
                (
                    "header_cta_text",
                    models.CharField(
                        blank=True,
                        default="Get a Quote",
                        help_text="Text for the header CTA button (max 50 characters).",
                        max_length=50,
                    ),
                ),
                (
                    "header_cta_link",
                    wagtail.fields.StreamField(
                        [("link", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("url", "External URL"),
                                        ("email", "Email"),
                                        ("phone", "Phone"),
                                        ("anchor", "Anchor"),
                                    ],
                                    "help_text": "Select the type of link.",
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Select an internal page.",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Enter an external URL (include https://).",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {
                                    "help_text": "Enter an email address.",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Custom display text for the link (optional).",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": None,
                                    "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 0),
                                        ("page", 1),
                                        ("url", 2),
                                        ("email", 3),
                                        ("phone", 4),
                                        ("anchor", 5),
                                        ("link_text", 6),
                                        ("open_in_new_tab", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Link destination for header CTA (optional, max 1).",
                    ),
                ),
                (
                    "mobile_cta_enabled",
                    models.BooleanField(
                        default=True, help_text="Enable the mobile sticky CTA bar."
                    ),
                ),
                (
                    "mobile_cta_phone_enabled",
                    models.BooleanField(
                        default=True, help_text="Show phone button in mobile CTA bar."
                    ),
                ),
                (
                    "mobile_cta_button_enabled",
                    models.BooleanField(
                        default=True, help_text="Show action button in mobile CTA bar."
                    ),
                ),
                (
                    "mobile_cta_button_text",
                    models.CharField(
                        blank=True,
                        default="Get a Quote",
                        help_text="Text for mobile CTA button (max 50 characters).",
                        max_length=50,
                    ),
                ),
                (
                    "mobile_cta_button_link",
                    wagtail.fields.StreamField(
                        [("link", 8)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("page", "Page"),
                                        ("url", "External URL"),
                                        ("email", "Email"),
                                        ("phone", "Phone"),
                                        ("anchor", "Anchor"),
                                    ],
                                    "help_text": "Select the type of link.",
                                },
                            ),
                            1: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {
                                    "help_text": "Select an internal page.",
                                    "required": False,
                                },
                            ),
                            2: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Enter an external URL (include https://).",
                                    "required": False,
                                },
                            ),
                            3: (
                                "wagtail.blocks.EmailBlock",
                                (),
                                {
                                    "help_text": "Enter an email address.",
                                    "required": False,
                                },
                            ),
                            4: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                                    "max_length": 30,
                                    "required": False,
                                },
                            ),
                            5: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            6: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Custom display text for the link (optional).",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            7: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": None,
                                    "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("link_type", 0),
                                        ("page", 1),
                                        ("url", 2),
                                        ("email", 3),
                                        ("phone", 4),
                                        ("anchor", 5),
                                        ("link_text", 6),
                                        ("open_in_new_tab", 7),
                                    ]
                                ],
                                {},
                            ),
                        },
                        help_text="Link destination for mobile CTA button (optional, max 1).",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Header Navigation",
            },
        ),
    ]
