# Generated by Django 5.2.9 on 2025-12-14 13:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_navigation", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footernavigation",
            name="social_facebook",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional override. Leave blank to use Site Settings value.",
            ),
        ),
        migrations.AlterField(
            model_name="footernavigation",
            name="social_instagram",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional override. Leave blank to use Site Settings value.",
            ),
        ),
        migrations.AlterField(
            model_name="footernavigation",
            name="social_linkedin",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional override. Leave blank to use Site Settings value.",
            ),
        ),
        migrations.AlterField(
            model_name="footernavigation",
            name="social_x",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional override. Leave blank to use Site Settings value.",
            ),
        ),
        migrations.AlterField(
            model_name="footernavigation",
            name="social_youtube",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional override. Leave blank to use Site Settings value.",
            ),
        ),
        migrations.AlterField(
            model_name="footernavigation",
            name="tagline",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional override. Leave blank to use Site Settings tagline. (max 255 characters)",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="headernavigation",
            name="menu_items",
            field=wagtail.fields.StreamField(
                [("item", 14)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Menu item label (max 50 characters).",
                            "max_length": 50,
                            "required": True,
                        },
                    ),
                    1: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [
                                ("page", "Page"),
                                ("url", "External URL"),
                                ("email", "Email"),
                                ("phone", "Phone"),
                                ("anchor", "Anchor"),
                            ],
                            "help_text": "Select the type of link.",
                        },
                    ),
                    2: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"help_text": "Select an internal page.", "required": False},
                    ),
                    3: (
                        "wagtail.blocks.URLBlock",
                        (),
                        {
                            "help_text": "Enter an external URL (include https://).",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.EmailBlock",
                        (),
                        {"help_text": "Enter an email address.", "required": False},
                    ),
                    5: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter a phone number (e.g., +44 20 7946 0958).",
                            "max_length": 30,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Enter an anchor ID (e.g., 'contact' or '#contact').",
                            "max_length": 100,
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Custom display text for the link (optional).",
                            "max_length": 255,
                            "required": False,
                        },
                    ),
                    8: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": None,
                            "help_text": "Force link to open in new tab. External URLs open in new tab by default.",
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("link_type", 1),
                                ("page", 2),
                                ("url", 3),
                                ("email", 4),
                                ("phone", 5),
                                ("anchor", 6),
                                ("link_text", 7),
                                ("open_in_new_tab", 8),
                            ]
                        ],
                        {
                            "help_text": "Link destination for this menu item.",
                            "required": True,
                        },
                    ),
                    10: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("link", 9)]],
                        {},
                    ),
                    11: (
                        "wagtail.blocks.ListBlock",
                        (10,),
                        {
                            "help_text": "Nested menu items (optional, max 8 items).",
                            "max_num": 8,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("link", 9), ("children", 11)]],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.ListBlock",
                        (12,),
                        {
                            "help_text": "Submenu items (optional, max 8 items).",
                            "max_num": 8,
                            "required": False,
                        },
                    ),
                    14: (
                        "wagtail.blocks.StructBlock",
                        [[("label", 0), ("link", 9), ("children", 13)]],
                        {},
                    ),
                },
                help_text="Top-level menu items (max 8).",
            ),
        ),
    ]
