"""Tests for superuser management."""

from __future__ import annotations

import subprocess
from pathlib import Path
from unittest.mock import MagicMock

import pytest

from cli.sum.exceptions import SuperuserError
from cli.sum.setup.auth import SuperuserManager, SuperuserResult, _escape_env_value
from cli.sum.utils.django import DjangoCommandExecutor
from cli.sum.utils.environment import ExecutionMode


@pytest.fixture
def mock_executor(tmp_path: Path) -> MagicMock:
    """Create a mocked DjangoCommandExecutor."""
    executor = MagicMock(spec=DjangoCommandExecutor)
    executor.project_path = tmp_path
    executor.mode = ExecutionMode.STANDALONE
    return executor


def test_escape_env_value_handles_quotes() -> None:
    """Test that special characters are properly escaped."""
    assert _escape_env_value("simple") == '"simple"'
    assert _escape_env_value('has "quotes"') == '"has \\"quotes\\""'
    assert _escape_env_value("has\\backslash") == '"has\\\\backslash"'
    assert _escape_env_value('complex"\\value') == '"complex\\"\\\\value"'


def test_user_exists_returns_true(mock_executor: MagicMock, tmp_path: Path) -> None:
    """Test user_exists returns True when user exists."""
    mock_executor.run_command.return_value = subprocess.CompletedProcess(
        args=[],
        returncode=0,
        stdout="True\n",
        stderr="",
    )

    manager = SuperuserManager(mock_executor, tmp_path)
    result = manager.user_exists("admin")

    assert result is True
    mock_executor.run_command.assert_called_once()
    call_args = mock_executor.run_command.call_args
    assert "shell" in call_args[0][0]
    assert "admin" in call_args[0][0][2]


def test_user_exists_returns_false(mock_executor: MagicMock, tmp_path: Path) -> None:
    """Test user_exists returns False when user doesn't exist."""
    mock_executor.run_command.return_value = subprocess.CompletedProcess(
        args=[],
        returncode=0,
        stdout="False\n",
        stderr="",
    )

    manager = SuperuserManager(mock_executor, tmp_path)
    result = manager.user_exists("admin")

    assert result is False


def test_create_new_user_success(mock_executor: MagicMock, tmp_path: Path) -> None:
    """Test creating a new superuser when user doesn't exist."""
    # First call: user_exists returns False
    # Second call: createsuperuser succeeds
    mock_executor.run_command.side_effect = [
        subprocess.CompletedProcess(args=[], returncode=0, stdout="False\n", stderr=""),
        subprocess.CompletedProcess(
            args=[],
            returncode=0,
            stdout="Superuser created successfully.\n",
            stderr="",
        ),
    ]

    manager = SuperuserManager(mock_executor, tmp_path)
    result = manager.create(
        username="testuser", email="test@example.com", password="testpass"
    )

    assert isinstance(result, SuperuserResult)
    assert result.success is True
    assert result.username == "testuser"
    assert result.created is True
    assert result.credentials_path == tmp_path / ".env.local"

    # Verify .env.local was created
    env_local = tmp_path / ".env.local"
    assert env_local.exists()
    content = env_local.read_text()
    assert 'DJANGO_SUPERUSER_USERNAME="testuser"' in content
    assert 'DJANGO_SUPERUSER_EMAIL="test@example.com"' in content
    assert 'DJANGO_SUPERUSER_PASSWORD="testpass"' in content
    assert "Auto-generated by sum init" in content
    assert "DO NOT COMMIT THIS FILE" in content


def test_create_existing_user_skips_creation(
    mock_executor: MagicMock, tmp_path: Path
) -> None:
    """Test that creating an existing user skips both creation and .env.local writing."""
    # user_exists returns True
    mock_executor.run_command.return_value = subprocess.CompletedProcess(
        args=[], returncode=0, stdout="True\n", stderr=""
    )

    manager = SuperuserManager(mock_executor, tmp_path)
    result = manager.create(
        username="admin", email="admin@example.com", password="admin"
    )

    assert isinstance(result, SuperuserResult)
    assert result.success is True
    assert result.username == "admin"
    assert result.created is False

    # Verify .env.local was NOT created
    env_local = tmp_path / ".env.local"
    assert not env_local.exists()

    # Verify createsuperuser was NOT called (only user_exists was called)
    assert mock_executor.run_command.call_count == 1


def test_create_user_failure_raises_error(
    mock_executor: MagicMock, tmp_path: Path
) -> None:
    """Test that superuser creation failure raises SuperuserError."""
    # First call: user_exists returns False
    # Second call: createsuperuser fails
    mock_executor.run_command.side_effect = [
        subprocess.CompletedProcess(args=[], returncode=0, stdout="False\n", stderr=""),
        subprocess.CompletedProcess(
            args=[],
            returncode=1,
            stdout="",
            stderr="Error: Username already exists",
        ),
    ]

    manager = SuperuserManager(mock_executor, tmp_path)

    with pytest.raises(SuperuserError, match="Creation failed"):
        manager.create(username="admin", email="admin@example.com", password="admin")

    # Verify .env.local was NOT created on failure
    env_local = tmp_path / ".env.local"
    assert not env_local.exists()


def test_create_passes_password_via_env(
    mock_executor: MagicMock, tmp_path: Path
) -> None:
    """Test that password is passed via DJANGO_SUPERUSER_PASSWORD env var."""
    mock_executor.run_command.side_effect = [
        subprocess.CompletedProcess(args=[], returncode=0, stdout="False\n", stderr=""),
        subprocess.CompletedProcess(
            args=[], returncode=0, stdout="Superuser created successfully.\n", stderr=""
        ),
    ]

    manager = SuperuserManager(mock_executor, tmp_path)
    manager.create(username="admin", email="admin@example.com", password="secret123")

    # Check second call (createsuperuser)
    createsuperuser_call = mock_executor.run_command.call_args_list[1]
    assert createsuperuser_call[1]["env"] == {"DJANGO_SUPERUSER_PASSWORD": "secret123"}


def test_create_with_special_characters(
    mock_executor: MagicMock, tmp_path: Path
) -> None:
    """Test that special characters in credentials are properly escaped."""
    mock_executor.run_command.side_effect = [
        subprocess.CompletedProcess(args=[], returncode=0, stdout="False\n", stderr=""),
        subprocess.CompletedProcess(
            args=[], returncode=0, stdout="Superuser created successfully.\n", stderr=""
        ),
    ]

    manager = SuperuserManager(mock_executor, tmp_path)
    result = manager.create(
        username="admin",
        email="test@example.com",
        password='p@ss"word\\with$pecial',
    )

    assert result.success is True
    assert result.created is True

    # Verify .env.local has properly escaped values
    env_local = tmp_path / ".env.local"
    content = env_local.read_text()
    assert 'DJANGO_SUPERUSER_PASSWORD="p@ss\\"word\\\\with$pecial"' in content


def test_superuser_manager_uses_provided_executor(
    tmp_path: Path, mock_executor: MagicMock
) -> None:
    """Test that SuperuserManager uses the provided executor and path."""
    manager = SuperuserManager(mock_executor, tmp_path)

    assert manager.django is mock_executor
    assert manager.project_path == tmp_path


def test_env_local_has_dated_header(mock_executor: MagicMock, tmp_path: Path) -> None:
    """Test that .env.local includes a dated header."""
    mock_executor.run_command.side_effect = [
        subprocess.CompletedProcess(args=[], returncode=0, stdout="False\n", stderr=""),
        subprocess.CompletedProcess(
            args=[], returncode=0, stdout="Superuser created successfully.\n", stderr=""
        ),
    ]

    manager = SuperuserManager(mock_executor, tmp_path)
    manager.create()

    env_local = tmp_path / ".env.local"
    content = env_local.read_text()

    # Verify header format
    lines = content.split("\n")
    assert lines[0] == "# .env.local"
    assert "# Auto-generated by sum init on" in lines[1]
    assert "# DO NOT COMMIT THIS FILE" in lines[2]


def test_env_local_has_restrictive_permissions(
    mock_executor: MagicMock, tmp_path: Path
) -> None:
    """Test that .env.local has restrictive permissions (0o600)."""
    mock_executor.run_command.side_effect = [
        subprocess.CompletedProcess(args=[], returncode=0, stdout="False\n", stderr=""),
        subprocess.CompletedProcess(
            args=[], returncode=0, stdout="Superuser created successfully.\n", stderr=""
        ),
    ]

    manager = SuperuserManager(mock_executor, tmp_path)
    manager.create()

    env_local = tmp_path / ".env.local"
    assert env_local.exists()

    # Check file permissions (owner read/write only)
    import stat

    file_mode = env_local.stat().st_mode
    assert stat.S_IMODE(file_mode) == 0o600


def test_user_exists_raises_on_command_failure(
    mock_executor: MagicMock, tmp_path: Path
) -> None:
    """Test user_exists raises SuperuserError when Django shell command fails."""
    mock_executor.run_command.return_value = subprocess.CompletedProcess(
        args=[], returncode=1, stdout="", stderr="Database connection error"
    )

    manager = SuperuserManager(mock_executor, tmp_path)

    with pytest.raises(SuperuserError, match="Failed to check if user 'admin' exists"):
        manager.user_exists("admin")


def test_user_exists_raises_on_unexpected_output(
    mock_executor: MagicMock, tmp_path: Path
) -> None:
    """Test user_exists raises SuperuserError when output is unexpected."""
    mock_executor.run_command.return_value = subprocess.CompletedProcess(
        args=[], returncode=0, stdout="unexpected output", stderr=""
    )

    manager = SuperuserManager(mock_executor, tmp_path)

    with pytest.raises(
        SuperuserError, match="Unexpected output when checking if user 'admin' exists"
    ):
        manager.user_exists("admin")


def test_create_error_handles_empty_stderr(
    mock_executor: MagicMock, tmp_path: Path
) -> None:
    """Test that creation error handles empty stderr gracefully."""
    mock_executor.run_command.side_effect = [
        subprocess.CompletedProcess(args=[], returncode=0, stdout="False\n", stderr=""),
        subprocess.CompletedProcess(
            args=[], returncode=1, stdout="Error in stdout", stderr=""
        ),
    ]

    manager = SuperuserManager(mock_executor, tmp_path)

    with pytest.raises(SuperuserError, match="Creation failed: Error in stdout"):
        manager.create()
