# Generated by Django 5.2.9 on 2025-12-08 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primary_color",
                    models.CharField(
                        blank=True,
                        help_text="Primary brand colour in hex format (e.g. #0055ff).",
                        max_length=7,
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        blank=True,
                        help_text="Secondary brand colour in hex format (e.g. #f97316).",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True,
                        help_text="Accent brand colour in hex format (e.g. #10b981).",
                        max_length=7,
                    ),
                ),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        help_text="Background colour for pages (e.g. #ffffff).",
                        max_length=7,
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        help_text="Default text colour (e.g. #0f172a).",
                        max_length=7,
                    ),
                ),
                (
                    "surface_color",
                    models.CharField(
                        blank=True,
                        help_text="Surface colour for cards and panels (e.g. #f8fafc).",
                        max_length=7,
                    ),
                ),
                (
                    "surface_elevated_color",
                    models.CharField(
                        blank=True,
                        help_text="Elevated surface colour for layered elements.",
                        max_length=7,
                    ),
                ),
                (
                    "text_light_color",
                    models.CharField(
                        blank=True,
                        help_text="Subtle text colour for muted labels.",
                        max_length=7,
                    ),
                ),
                (
                    "heading_font",
                    models.CharField(
                        blank=True,
                        help_text="Google Fonts family name for headings.",
                        max_length=100,
                    ),
                ),
                (
                    "body_font",
                    models.CharField(
                        blank=True,
                        help_text="Google Fonts family name for body text.",
                        max_length=100,
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        help_text="Company or brand name displayed across the site.",
                        max_length=255,
                    ),
                ),
                (
                    "tagline",
                    models.CharField(
                        blank=True,
                        help_text="Short tagline or strapline.",
                        max_length=255,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        help_text="Primary contact phone number.",
                        max_length=50,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Primary contact email address.",
                        max_length=254,
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True,
                        help_text="Postal address displayed in footers or contact sections.",
                    ),
                ),
                (
                    "business_hours",
                    models.TextField(
                        blank=True, help_text="Business hours text (free-form)."
                    ),
                ),
                ("facebook_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("youtube_url", models.URLField(blank=True)),
                ("tiktok_url", models.URLField(blank=True)),
                (
                    "favicon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "footer_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "header_logo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
