# Generated by Django 5.2.9 on 2025-12-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="og_default_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Default image for social sharing (Open Graph).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
