# Generated by Django 5.2.9 on 2025-12-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core", "0002_sitesettings_og_default_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="ga_measurement_id",
            field=models.CharField(
                blank=True,
                help_text="Google Analytics 4 Measurement ID (e.g. G-XXXXXXXXXX).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="gtm_container_id",
            field=models.CharField(
                blank=True,
                help_text="Google Tag Manager Container ID (e.g. GTM-XXXXXX).",
                max_length=20,
            ),
        ),
    ]
