# Generated by Django 5.2.9 on 2025-12-15 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core", "0003_sitesettings_ga_measurement_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="robots_txt",
            field=models.TextField(
                blank=True,
                help_text="Custom robots.txt content. If blank, defaults to allowing all bots. Sitemap reference will be added automatically.",
            ),
        ),
    ]
