# Generated by Django 5.2.9 on 2025-12-15 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core", "0004_add_robots_txt_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="zapier_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable Zapier webhook integration for new leads.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="zapier_webhook_url",
            field=models.URLField(
                blank=True, help_text="Zapier webhook URL for lead notifications."
            ),
        ),
    ]
