# Generated by Django 5.2.9 on 2025-12-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core", "0005_sitesettings_zapier_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="notification_from_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address used in the 'From' header (e.g. leads@acme.com).",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notification_from_name",
            field=models.CharField(
                blank=True,
                help_text="Name used in the 'From' header (e.g. 'ACME Corp Leads').",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notification_reply_to_email",
            field=models.EmailField(
                blank=True,
                help_text="Email address for the 'Reply-To' header (e.g. sales@acme.com).",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notification_subject_prefix",
            field=models.CharField(
                blank=True,
                help_text="Optional prefix for the email subject (e.g. '[New Lead]').",
                max_length=50,
            ),
        ),
    ]
