# Generated by Django 5.2.9 on 2025-12-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core", "0006_sitesettings_notification_from_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="established_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
