# Generated by Django 5.2.9 on 2025-12-24 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core", "0007_sitesettings_established_year"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_banner_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, analytics load only after a visitor accepts the banner; when disabled, analytics load immediately.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_consent_version",
            field=models.CharField(
                default="1",
                help_text="Increment this version when consent text changes to trigger a new prompt.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cookie_policy_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to your cookie policy page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="privacy_policy_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to your privacy policy page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="terms_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional link to your terms page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.page",
            ),
        ),
    ]
