# Generated by Django 5.2.9 on 2025-12-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_leads", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadSourceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "utm_source",
                    models.CharField(
                        blank=True,
                        help_text="Match leads with this utm_source value (case-insensitive, exact match).",
                        max_length=100,
                    ),
                ),
                (
                    "utm_medium",
                    models.CharField(
                        blank=True,
                        help_text="Match leads with this utm_medium value (case-insensitive, exact match).",
                        max_length=100,
                    ),
                ),
                (
                    "referrer_contains",
                    models.CharField(
                        blank=True,
                        help_text="Match leads where referrer_url contains this string (case-insensitive).",
                        max_length=200,
                    ),
                ),
                (
                    "derived_source",
                    models.CharField(
                        choices=[
                            ("google_ads", "Google Ads"),
                            ("meta_ads", "Meta Ads"),
                            ("bing_ads", "Bing Ads"),
                            ("seo", "SEO"),
                            ("direct", "Direct"),
                            ("referral", "Referral"),
                            ("offline", "Offline"),
                            ("unknown", "Unknown"),
                        ],
                        help_text="The lead_source value to assign when this rule matches.",
                        max_length=50,
                    ),
                ),
                (
                    "derived_source_detail",
                    models.CharField(
                        blank=True,
                        help_text="Optional detail to add to lead_source_detail.",
                        max_length=200,
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        default=100,
                        help_text="Lower numbers are higher priority. First matching rule wins.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive rules are skipped during matching.",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional descriptive name for this rule.",
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Source Rule",
                "verbose_name_plural": "Lead Source Rules",
                "ordering": ["priority", "id"],
            },
        ),
        migrations.AddField(
            model_name="lead",
            name="landing_page_url",
            field=models.URLField(
                blank=True,
                help_text="First page URL the visitor landed on.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google_ads", "Google Ads"),
                    ("meta_ads", "Meta Ads"),
                    ("bing_ads", "Bing Ads"),
                    ("seo", "SEO"),
                    ("direct", "Direct"),
                    ("referral", "Referral"),
                    ("offline", "Offline"),
                    ("unknown", "Unknown"),
                ],
                help_text="Derived source category (e.g. 'google_ads', 'seo').",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="lead_source_detail",
            field=models.TextField(
                blank=True,
                help_text="Additional source details for debugging/reporting.",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="page_url",
            field=models.URLField(
                blank=True,
                help_text="Page URL where form was submitted.",
                max_length=500,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="referrer_url",
            field=models.URLField(
                blank=True, help_text="HTTP referer header value.", max_length=500
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_campaign",
            field=models.CharField(
                blank=True, help_text="UTM campaign parameter.", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_content",
            field=models.CharField(
                blank=True,
                help_text="UTM content parameter (ad variant).",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_medium",
            field=models.CharField(
                blank=True,
                help_text="UTM medium parameter (e.g. 'cpc', 'email').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_source",
            field=models.CharField(
                blank=True,
                help_text="UTM source parameter (e.g. 'google', 'facebook').",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="utm_term",
            field=models.CharField(
                blank=True, help_text="UTM term parameter (keywords).", max_length=100
            ),
        ),
    ]
