# Generated by Django 5.2.9 on 2025-12-14 14:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_leads", "0002_leadsourcerule_lead_landing_page_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={
                "ordering": ["-submitted_at"],
                "permissions": [("export_lead", "Can export leads to CSV")],
            },
        ),
    ]
