# Generated by Django 5.2.9 on 2025-12-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_leads", "0003_alter_lead_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="email_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of email delivery attempts."
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_last_error",
            field=models.TextField(
                blank=True, help_text="Last error message if email delivery failed."
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the email notification was successfully sent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of email notification delivery.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="webhook_attempts",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of webhook delivery attempts."
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="webhook_last_error",
            field=models.TextField(
                blank=True, help_text="Last error message if webhook delivery failed."
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="webhook_last_status_code",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="HTTP status code from last webhook attempt.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="webhook_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the webhook notification was successfully sent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="webhook_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("disabled", "Disabled"),
                ],
                default="pending",
                help_text="Status of webhook notification delivery.",
                max_length=20,
            ),
        ),
    ]
