# Generated by Django 5.2.9 on 2025-12-15 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_leads", "0004_lead_integration_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="zapier_attempt_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of Zapier delivery attempts."
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="zapier_last_attempt_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the Zapier webhook was last attempted.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="zapier_last_error",
            field=models.TextField(
                blank=True,
                help_text="Last error message if Zapier delivery failed (truncated).",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="zapier_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("disabled", "Disabled"),
                ],
                default="pending",
                help_text="Status of Zapier webhook delivery.",
                max_length=20,
            ),
        ),
    ]
