# Generated by Django 5.2.9 on 2025-12-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_leads", "0005_lead_zapier_status_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="form_notification_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("disabled", "Disabled"),
                ],
                default="disabled",
                help_text="Status of dynamic form admin notification delivery.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="form_notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the dynamic form admin notification was sent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="form_notification_last_error",
            field=models.TextField(
                blank=True,
                help_text="Last error message for dynamic form admin notification.",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="form_notification_attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of dynamic form admin notification attempts.",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="auto_reply_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("disabled", "Disabled"),
                ],
                default="disabled",
                help_text="Status of dynamic form auto-reply delivery.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="auto_reply_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the dynamic form auto-reply was sent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="auto_reply_last_error",
            field=models.TextField(
                blank=True,
                help_text="Last error message for dynamic form auto-reply.",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="auto_reply_attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of dynamic form auto-reply attempts.",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="form_webhook_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_progress", "In progress"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("disabled", "Disabled"),
                ],
                default="disabled",
                help_text="Status of dynamic form webhook delivery.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="form_webhook_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the dynamic form webhook was sent.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="form_webhook_last_error",
            field=models.TextField(
                blank=True,
                help_text="Last error message for dynamic form webhook delivery.",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="form_webhook_attempts",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of dynamic form webhook attempts.",
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="form_webhook_last_status_code",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="HTTP status code from last dynamic form webhook attempt.",
                null=True,
            ),
        ),
    ]
