# Generated by Django 5.2.9 on 2025-12-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_pages", "0001_initial"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="standardpage",
            name="meta_description",
            field=models.TextField(
                blank=True,
                help_text="Optional. Brief summary for search engines (recommended max 160 characters).",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. If blank, defaults to “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional. If blank, uses the page featured image (if present), otherwise the site default OG image.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
            ),
        ),
    ]
