# Generated by Django 5.2.9 on 2025-12-14 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_pages", "0004_serviceindexpage_servicepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceindexpage",
            name="seo_nofollow",
            field=models.BooleanField(
                default=False,
                help_text="If checked, search engines will not follow links on this page (nofollow).",
                verbose_name="No-Follow",
            ),
        ),
        migrations.AddField(
            model_name="serviceindexpage",
            name="seo_noindex",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will be hidden from search engines (noindex).",
                verbose_name="No-Index",
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="seo_nofollow",
            field=models.BooleanField(
                default=False,
                help_text="If checked, search engines will not follow links on this page (nofollow).",
                verbose_name="No-Follow",
            ),
        ),
        migrations.AddField(
            model_name="servicepage",
            name="seo_noindex",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will be hidden from search engines (noindex).",
                verbose_name="No-Index",
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="seo_nofollow",
            field=models.BooleanField(
                default=False,
                help_text="If checked, search engines will not follow links on this page (nofollow).",
                verbose_name="No-Follow",
            ),
        ),
        migrations.AddField(
            model_name="standardpage",
            name="seo_noindex",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will be hidden from search engines (noindex).",
                verbose_name="No-Index",
            ),
        ),
    ]
