# Generated by Django 5.2.9 on 2025-12-25 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sum_core_pages",
            "0009_alter_serviceindexpage_intro_alter_servicepage_body_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Category name (e.g., 'News', 'Tutorials', 'Case Studies')",
                        max_length=100,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly identifier", max_length=100, unique=True
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional category description for SEO",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "verbose_name_plural": "Categories",
            },
        ),
    ]
