# Generated by Django 5.2.9 on 2025-12-25 17:48

import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_pages", "0010_category"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogIndexPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional. If blank, defaults to “{page title} | {site name}”.",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. Brief summary for search engines (recommended max 160 characters).",
                        max_length=160,
                    ),
                ),
                (
                    "seo_noindex",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this page will be hidden from search engines (noindex).",
                        verbose_name="No-Index",
                    ),
                ),
                (
                    "seo_nofollow",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, search engines will not follow links on this page (nofollow).",
                        verbose_name="No-Follow",
                    ),
                ),
                (
                    "intro",
                    wagtail.fields.RichTextField(
                        blank=True,
                        help_text="Optional intro text displayed above the post listing.",
                    ),
                ),
                (
                    "posts_per_page",
                    models.IntegerField(
                        default=10,
                        help_text="Number of posts to display per page.",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. If blank, uses the page featured image (if present), otherwise the site default OG image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Index Page",
                "verbose_name_plural": "Blog Index Pages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
        migrations.CreateModel(
            name="BlogPostPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional. If blank, defaults to “{page title} | {site name}”.",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. Brief summary for search engines (recommended max 160 characters).",
                        max_length=160,
                    ),
                ),
                (
                    "seo_noindex",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this page will be hidden from search engines (noindex).",
                        verbose_name="No-Index",
                    ),
                ),
                (
                    "seo_nofollow",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, search engines will not follow links on this page (nofollow).",
                        verbose_name="No-Follow",
                    ),
                ),
                (
                    "published_date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Publication date used for ordering in blog listings.",
                    ),
                ),
                ("body", wagtail.fields.RichTextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="sum_core_pages.category",
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. If blank, uses the page featured image (if present), otherwise the site default OG image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post Page",
                "verbose_name_plural": "Blog Post Pages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
