# Generated by Django 5.2.9 on 2025-12-25 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sum_core_pages",
            "0011_alter_serviceindexpage_intro_alter_servicepage_body_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="published_date",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                help_text="Date this post was published",
            ),
        ),
    ]
