# Generated by Django 5.2.9 on 2025-12-25 17:27

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sum_core_pages",
            "0012_alter_blogpostpage_published_date",
        ),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="LegalPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional. If blank, defaults to “{page title} | {site name}”.",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. Brief summary for search engines (recommended max 160 characters).",
                        max_length=160,
                    ),
                ),
                (
                    "seo_noindex",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this page will be hidden from search engines (noindex).",
                        verbose_name="No-Index",
                    ),
                ),
                (
                    "seo_nofollow",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, search engines will not follow links on this page (nofollow).",
                        verbose_name="No-Follow",
                    ),
                ),
                (
                    "last_updated",
                    models.DateField(
                        blank=True,
                        help_text="Optional date displayed near the page title.",
                        null=True,
                    ),
                ),
                (
                    "sections",
                    wagtail.fields.StreamField(
                        [("section", 3)],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Anchor ID used for in-page links (use lowercase with hyphens).",
                                    "required": True,
                                },
                            ),
                            1: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Section heading.", "required": True},
                            ),
                            2: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                    ],
                                    "help_text": "Section content. Use H3/H4 for nested headings; avoid H1/H2.",
                                    "required": True,
                                },
                            ),
                            3: (
                                "wagtail.blocks.StructBlock",
                                [[("anchor", 0), ("heading", 1), ("body", 2)]],
                                {},
                            ),
                        },
                        help_text="Add sections with anchors, headings, and body copy.",
                        null=True,
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. If blank, uses the page featured image (if present), otherwise the site default OG image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Legal Page",
                "verbose_name_plural": "Legal Pages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
