# Generated by Django 5.2.9 on 2025-12-26 00:00

import wagtail.fields
from django.core.validators import MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_pages", "0012_alter_blogpostpage_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogindexpage",
            name="intro",
            field=wagtail.fields.RichTextField(
                blank=True,
                help_text="Optional intro text displayed above the post listing.",
            ),
        ),
        migrations.AddField(
            model_name="blogindexpage",
            name="posts_per_page",
            field=models.IntegerField(
                default=10,
                help_text="Number of posts to display per page.",
                validators=[MinValueValidator(1)],
            ),
        ),
    ]
