# Generated by Django 5.2.9 on 2025-12-25 22:34

from django.db import migrations
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_pages", "0013_blogindexpage_fields"),
        ("sum_core_pages", "0013_legalpage"),
    ]

    operations: list[Operation] = []
