# Generated by Django 5.2.9 on 2025-12-14 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "honeypot_field_name",
                    models.CharField(
                        default="company",
                        help_text="Name of the honeypot field. If filled, submission is rejected as spam.",
                        max_length=50,
                    ),
                ),
                (
                    "rate_limit_per_ip_per_hour",
                    models.PositiveIntegerField(
                        default=20,
                        help_text="Maximum form submissions allowed per IP address per hour.",
                    ),
                ),
                (
                    "min_seconds_to_submit",
                    models.PositiveIntegerField(
                        default=3,
                        help_text="Minimum seconds between form render and submission. Faster submissions are rejected.",
                    ),
                ),
                (
                    "lead_notification_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for lead notifications. If blank, falls back to environment variable.",
                        max_length=254,
                    ),
                ),
                (
                    "default_form_type",
                    models.CharField(
                        blank=True,
                        help_text="Default form type if not specified in submission.",
                        max_length=50,
                    ),
                ),
                (
                    "site",
                    models.OneToOneField(
                        help_text="The site this configuration applies to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_configuration",
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Configuration",
                "verbose_name_plural": "Form Configurations",
            },
        ),
    ]
