# Generated by Django 5.2.9 on 2025-12-24 21:52

import django.db.models.deletion
import sum_core.forms.models
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_forms", "0001_initial"),
        ("wagtailcore", "0094_alter_page_locale"),
    ]

    operations = [
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Reference name used in the admin.", max_length=255
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Unique identifier for this form within the site.",
                        max_length=100,
                    ),
                ),
                (
                    "fields",
                    wagtail.fields.StreamField(
                        [],
                        blank=True,
                        block_lookup={},
                        help_text="Form field blocks will be added in BLOG.002.",
                    ),
                ),
                (
                    "success_message",
                    models.TextField(
                        default="Thank you for your submission!",
                        help_text="Message shown after successful submission.",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Deactivate to hide this form without deleting it.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "email_notification_enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Send notification emails on submission.",
                    ),
                ),
                (
                    "notification_emails",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of recipient emails.",
                        validators=[
                            sum_core.forms.models.validate_comma_separated_emails
                        ],
                    ),
                ),
                (
                    "auto_reply_enabled",
                    models.BooleanField(
                        default=False, help_text="Send auto-reply to the submitter."
                    ),
                ),
                (
                    "auto_reply_subject",
                    models.CharField(
                        blank=True,
                        help_text="Subject for auto-reply emails.",
                        max_length=255,
                    ),
                ),
                (
                    "auto_reply_body",
                    models.TextField(
                        blank=True, help_text="Body content for auto-reply emails."
                    ),
                ),
                (
                    "webhook_enabled",
                    models.BooleanField(
                        default=False, help_text="Send webhook on submission."
                    ),
                ),
                (
                    "webhook_url",
                    models.URLField(
                        blank=True, help_text="Endpoint to receive submission payloads."
                    ),
                ),
                (
                    "site",
                    models.ForeignKey(
                        help_text="Site this form definition belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_definitions",
                        to="wagtailcore.site",
                    ),
                ),
            ],
            options={
                "verbose_name": "Form Definition",
                "verbose_name_plural": "Form Definitions",
                "ordering": ["-created_at"],
                "unique_together": {("site", "slug")},
            },
        ),
    ]
