# Generated by Django 5.2.9 on 2025-12-24 22:49

import django.core.validators
import re
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_forms", "0002_formdefinition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdefinition",
            name="fields",
            field=wagtail.fields.StreamField(
                [
                    ("text_input", 7),
                    ("email_input", 7),
                    ("phone_input", 9),
                    ("textarea", 12),
                    ("select", 18),
                    ("checkbox", 20),
                    ("checkbox_group", 21),
                    ("radio_buttons", 21),
                    ("file_upload", 24),
                    ("section_heading", 27),
                    ("help_text", 29),
                ],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Unique field identifier (e.g., 'email', 'phone').",
                            "required": True,
                            "validators": [
                                django.core.validators.RegexValidator(
                                    re.compile("^[-a-zA-Z0-9_]+\\Z"),
                                    "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                                    "invalid",
                                )
                            ],
                        },
                    ),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Field label shown to users.", "required": True},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional help text below field.",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": True,
                            "help_text": "Mark field as required.",
                            "required": False,
                        },
                    ),
                    4: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional CSS classes for styling.",
                            "required": False,
                        },
                    ),
                    5: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 255,
                            "help_text": "Maximum number of characters allowed.",
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    6: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Optional placeholder text shown in the field.",
                            "required": False,
                        },
                    ),
                    7: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_name", 0),
                                ("label", 1),
                                ("help_text", 2),
                                ("required", 3),
                                ("css_class", 4),
                                ("max_length", 5),
                                ("placeholder", 6),
                            ]
                        ],
                        {},
                    ),
                    8: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": 'Optional input mask (e.g., "(###) ###-####").',
                            "required": False,
                        },
                    ),
                    9: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_name", 0),
                                ("label", 1),
                                ("help_text", 2),
                                ("required", 3),
                                ("css_class", 4),
                                ("format_mask", 8),
                                ("placeholder", 6),
                            ]
                        ],
                        {},
                    ),
                    10: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 4,
                            "help_text": "Number of visible text rows.",
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    11: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "help_text": "Optional maximum number of characters allowed.",
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    12: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_name", 0),
                                ("label", 1),
                                ("help_text", 2),
                                ("required", 3),
                                ("css_class", 4),
                                ("rows", 10),
                                ("max_length", 11),
                                ("placeholder", 6),
                            ]
                        ],
                        {},
                    ),
                    13: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Value submitted when selected.",
                            "required": True,
                        },
                    ),
                    14: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Display label shown to users.",
                            "required": True,
                        },
                    ),
                    15: (
                        "wagtail.blocks.StructBlock",
                        [[("value", 13), ("label", 14)]],
                        {},
                    ),
                    16: (
                        "wagtail.blocks.StreamBlock",
                        [[("option", 15)]],
                        {"required": True},
                    ),
                    17: (
                        "wagtail.blocks.BooleanBlock",
                        (),
                        {
                            "default": False,
                            "help_text": "Allow multiple selections.",
                            "required": False,
                        },
                    ),
                    18: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_name", 0),
                                ("label", 1),
                                ("help_text", 2),
                                ("required", 3),
                                ("css_class", 4),
                                ("choices", 16),
                                ("allow_multiple", 17),
                            ]
                        ],
                        {},
                    ),
                    19: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "default": "yes",
                            "help_text": "Value submitted when the checkbox is checked.",
                            "required": False,
                        },
                    ),
                    20: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_name", 0),
                                ("label", 1),
                                ("help_text", 2),
                                ("required", 3),
                                ("css_class", 4),
                                ("checked_value", 19),
                            ]
                        ],
                        {},
                    ),
                    21: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_name", 0),
                                ("label", 1),
                                ("help_text", 2),
                                ("required", 3),
                                ("css_class", 4),
                                ("choices", 16),
                            ]
                        ],
                        {},
                    ),
                    22: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Comma-separated allowed extensions (e.g., '.pdf,.doc,.docx').",
                            "required": True,
                        },
                    ),
                    23: (
                        "wagtail.blocks.IntegerBlock",
                        (),
                        {
                            "default": 10,
                            "help_text": "Maximum file size in megabytes.",
                            "min_value": 1,
                            "required": False,
                        },
                    ),
                    24: (
                        "wagtail.blocks.StructBlock",
                        [
                            [
                                ("field_name", 0),
                                ("label", 1),
                                ("help_text", 2),
                                ("required", 3),
                                ("css_class", 4),
                                ("allowed_extensions", 22),
                                ("max_file_size_mb", 23),
                            ]
                        ],
                        {},
                    ),
                    25: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"help_text": "Section heading text.", "required": True},
                    ),
                    26: (
                        "wagtail.blocks.ChoiceBlock",
                        [],
                        {
                            "choices": [("h2", "H2"), ("h3", "H3"), ("h4", "H4")],
                            "default": "h2",
                            "help_text": "Heading level.",
                        },
                    ),
                    27: (
                        "wagtail.blocks.StructBlock",
                        [[("heading", 25), ("level", 26)]],
                        {},
                    ),
                    28: (
                        "wagtail.blocks.RichTextBlock",
                        (),
                        {
                            "features": ["bold", "italic", "ol", "ul", "link"],
                            "help_text": "Helper copy or instructions.",
                            "required": True,
                        },
                    ),
                    29: ("wagtail.blocks.StructBlock", [[("text", 28)]], {}),
                },
                help_text="Form field blocks for dynamic forms.",
            ),
        ),
    ]
