# Generated by Django 5.2.9 on 2025-12-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sum_core_forms", "0003_alter_formdefinition_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdefinition",
            name="webhook_signing_secret",
            field=models.CharField(
                blank=True,
                help_text="Optional shared secret used to sign webhook payloads.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="webhook_field_allowlist",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Comma-separated list of form field keys allowed in webhook payloads."
                ),
            ),
        ),
        migrations.AddField(
            model_name="formdefinition",
            name="webhook_field_denylist",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Comma-separated list of form field keys to exclude from webhook payloads."
                ),
            ),
        ),
    ]
