# Generated by Django 5.2.9 on 2025-12-15 18:32

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional. If blank, defaults to “{page title} | {site name}”.",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. Brief summary for search engines (recommended max 160 characters).",
                        max_length=160,
                    ),
                ),
                (
                    "seo_noindex",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this page will be hidden from search engines (noindex).",
                        verbose_name="No-Index",
                    ),
                ),
                (
                    "seo_nofollow",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, search engines will not follow links on this page (nofollow).",
                        verbose_name="No-Follow",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. If blank, uses the page featured image (if present), otherwise the site default OG image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
