# Generated by Django 5.2.9 on 2025-12-10 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_homepage_body"),
    ]

    operations = []
