# Generated by Django 5.2.9 on 2025-12-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_homepage_seo_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homepage",
            options={"verbose_name": "Home Page", "verbose_name_plural": "Home Pages"},
        ),
        migrations.AlterField(
            model_name="homepage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional. If blank, defaults to “{page title} | {site name}”.",
                max_length=60,
            ),
        ),
    ]
