# Generated by Django 5.2.9 on 2025-12-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_alter_homepage_options_alter_homepage_meta_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="seo_nofollow",
            field=models.BooleanField(
                default=False,
                help_text="If checked, search engines will not follow links on this page (nofollow).",
                verbose_name="No-Follow",
            ),
        ),
        migrations.AddField(
            model_name="homepage",
            name="seo_noindex",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this page will be hidden from search engines (noindex).",
                verbose_name="No-Index",
            ),
        ),
    ]
