# Generated by Django 5.2.9 on 2025-12-16 20:46

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional. If blank, defaults to “{page title} | {site name}”.",
                        max_length=60,
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        blank=True,
                        help_text="Optional. Brief summary for search engines (recommended max 160 characters).",
                        max_length=160,
                    ),
                ),
                (
                    "seo_noindex",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, this page will be hidden from search engines (noindex).",
                        verbose_name="No-Index",
                    ),
                ),
                (
                    "seo_nofollow",
                    models.BooleanField(
                        default=False,
                        help_text="If checked, search engines will not follow links on this page (nofollow).",
                        verbose_name="No-Follow",
                    ),
                ),
                ("intro", wagtail.fields.RichTextField(blank=True)),
                (
                    "body",
                    wagtail.fields.StreamField(
                        [
                            ("hero_image", 14),
                            ("hero_gradient", 16),
                            ("service_cards", 29),
                            ("testimonials", 39),
                            ("gallery", 47),
                            ("hero", 57),
                            ("trust_strip", 60),
                            ("trust_strip_logos", 67),
                            ("stats", 76),
                            ("process", 84),
                            ("faq", 92),
                            ("features", 96),
                            ("comparison", 100),
                            ("portfolio", 110),
                            ("editorial_header", 114),
                            ("content", 116),
                            ("quote", 119),
                            ("image_block", 123),
                            ("buttons", 130),
                            ("spacer", 132),
                            ("divider", 134),
                            ("contact_form", 140),
                            ("quote_request_form", 147),
                            ("rich_text", 148),
                        ],
                        blank=True,
                        block_lookup={
                            0: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["italic"],
                                    "help_text": "Main heading. Highlight text and use 'Italic' to apply the accent styling.",
                                    "required": True,
                                },
                            ),
                            1: ("wagtail.blocks.TextBlock", (), {"required": False}),
                            2: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 100, "required": True},
                            ),
                            3: ("wagtail.blocks.URLBlock", (), {"required": True}),
                            4: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                        ("outline", "Outline"),
                                    ]
                                },
                            ),
                            5: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {"default": False, "required": False},
                            ),
                            6: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 2),
                                        ("url", 3),
                                        ("style", 4),
                                        ("open_in_new_tab", 5),
                                    ]
                                ],
                                {},
                            ),
                            7: (
                                "wagtail.blocks.ListBlock",
                                (6,),
                                {
                                    "label": "CTA Buttons",
                                    "max_num": 2,
                                    "min_num": 0,
                                    "required": False,
                                },
                            ),
                            8: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "label": "Status / Eyebrow",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            9: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"required": True},
                            ),
                            10: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Alt text for accessibility",
                                    "max_length": 150,
                                    "required": True,
                                },
                            ),
                            11: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("none", "No overlay"),
                                        ("light", "Light"),
                                        ("medium", "Medium"),
                                        ("strong", "Strong"),
                                    ],
                                    "help_text": "Dark overlay opacity for text contrast",
                                },
                            ),
                            12: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. 'Est. Annual Savings'",
                                    "label": "Floating Card Label",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            13: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. '£2,450'",
                                    "label": "Floating Card Value",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            14: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("headline", 0),
                                        ("subheadline", 1),
                                        ("ctas", 7),
                                        ("status", 8),
                                        ("image", 9),
                                        ("image_alt", 10),
                                        ("overlay_opacity", 11),
                                        ("floating_card_label", 12),
                                        ("floating_card_value", 13),
                                    ]
                                ],
                                {"group": "Hero"},
                            ),
                            15: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary gradient"),
                                        ("secondary", "Secondary gradient"),
                                        ("accent", "Accent gradient"),
                                    ]
                                },
                            ),
                            16: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("headline", 0),
                                        ("subheadline", 1),
                                        ("ctas", 7),
                                        ("status", 8),
                                        ("gradient_style", 15),
                                    ]
                                ],
                                {"group": "Hero"},
                            ),
                            17: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Short label above the heading (optional).",
                                    "max_length": 120,
                                    "required": False,
                                },
                            ),
                            18: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["italic", "bold"],
                                    "help_text": "Section heading. Use Italic for accent color.",
                                    "required": True,
                                },
                            ),
                            19: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Short supporting paragraph.",
                                    "required": False,
                                },
                            ),
                            20: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Emoji or short icon text (optional)",
                                    "max_length": 4,
                                    "required": False,
                                },
                            ),
                            21: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Allows proper image/icon; render as the primary visual if present.",
                                    "required": False,
                                },
                            ),
                            22: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 120, "required": True},
                            ),
                            23: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "ul",
                                        "ol",
                                        "document-link",
                                    ],
                                    "help_text": "Limited to paragraphs + basic inline formatting.",
                                    "required": False,
                                },
                            ),
                            24: ("wagtail.blocks.URLBlock", (), {"required": False}),
                            25: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Defaults to “Learn more” if left blank.",
                                    "max_length": 50,
                                    "required": False,
                                },
                            ),
                            26: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("icon", 20),
                                        ("image", 21),
                                        ("title", 22),
                                        ("description", 23),
                                        ("link_url", 24),
                                        ("link_label", 25),
                                    ]
                                ],
                                {},
                            ),
                            27: (
                                "wagtail.blocks.ListBlock",
                                (26,),
                                {"max_num": 12, "min_num": 1},
                            ),
                            28: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("default", "Default"),
                                        ("tight", "Tight spacing"),
                                    ],
                                    "required": False,
                                },
                            ),
                            29: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 17),
                                        ("heading", 18),
                                        ("intro", 19),
                                        ("cards", 27),
                                        ("layout_style", 28),
                                    ]
                                ],
                                {"group": "Services"},
                            ),
                            30: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small text above heading, e.g. 'Client Stories'.",
                                    "required": False,
                                },
                            ),
                            31: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic"],
                                    "help_text": "Main section heading. Use italics for accent styling.",
                                    "required": False,
                                },
                            ),
                            32: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Customer quote or review text.",
                                    "required": True,
                                },
                            ),
                            33: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Name of the customer.",
                                    "required": True,
                                },
                            ),
                            34: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Company or context (optional).",
                                    "required": False,
                                },
                            ),
                            35: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Optional headshot or avatar.",
                                    "required": False,
                                },
                            ),
                            36: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "help_text": "Optional rating from 1 to 5 stars.",
                                    "max_value": 5,
                                    "min_value": 1,
                                    "required": False,
                                },
                            ),
                            37: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("quote", 32),
                                        ("author_name", 33),
                                        ("company", 34),
                                        ("photo", 35),
                                        ("rating", 36),
                                    ]
                                ],
                                {},
                            ),
                            38: (
                                "wagtail.blocks.ListBlock",
                                (37,),
                                {
                                    "help_text": "One or more testimonial cards.",
                                    "max_num": 12,
                                    "min_num": 1,
                                },
                            ),
                            39: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 30),
                                        ("heading", 31),
                                        ("testimonials", 38),
                                    ]
                                ],
                                {"group": "Sections"},
                            ),
                            40: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small text above heading, e.g. 'Selected Works'.",
                                    "max_length": 80,
                                    "required": False,
                                },
                            ),
                            41: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Optional supporting text.",
                                    "required": False,
                                },
                            ),
                            42: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {"help_text": "Project photo.", "required": True},
                            ),
                            43: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "For screen readers. If blank, the image title will be used.",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            44: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Short caption, e.g. location or project type.",
                                    "max_length": 255,
                                    "required": False,
                                },
                            ),
                            45: (
                                "wagtail.blocks.StructBlock",
                                [[("image", 42), ("alt_text", 43), ("caption", 44)]],
                                {},
                            ),
                            46: (
                                "wagtail.blocks.ListBlock",
                                (45,),
                                {
                                    "help_text": "Add 1–24 images to the gallery.",
                                    "max_num": 24,
                                    "min_num": 1,
                                },
                            ),
                            47: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 40),
                                        ("heading", 31),
                                        ("intro", 41),
                                        ("images", 46),
                                    ]
                                ],
                                {"group": "Sections"},
                            ),
                            48: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. Available for Q1 2025",
                                    "required": False,
                                },
                            ),
                            49: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Main heading. Use html tags like <span class='italic-accent'> for styling.",
                                    "required": True,
                                },
                            ),
                            50: ("wagtail.blocks.TextBlock", (), {"required": True}),
                            51: ("wagtail.blocks.CharBlock", (), {"required": True}),
                            52: (
                                "wagtail.blocks.PageChooserBlock",
                                (),
                                {"required": False},
                            ),
                            53: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("btn-primary", "Primary"),
                                        ("btn-outline", "Outline"),
                                    ]
                                },
                            ),
                            54: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("label", 51),
                                        ("link", 24),
                                        ("page", 52),
                                        ("style", 53),
                                    ]
                                ],
                                {"required": False},
                            ),
                            55: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. Est. Annual Savings",
                                    "required": False,
                                },
                            ),
                            56: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "e.g. £2,450", "required": False},
                            ),
                            57: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("status_text", 48),
                                        ("title", 49),
                                        ("description", 50),
                                        ("primary_cta", 54),
                                        ("secondary_cta", 54),
                                        ("image", 9),
                                        ("float_card_label", 55),
                                        ("float_card_value", 56),
                                    ]
                                ],
                                {"group": "Legacy Sections"},
                            ),
                            58: ("wagtail.blocks.StructBlock", [[("text", 51)]], {}),
                            59: ("wagtail.blocks.ListBlock", (58,), {}),
                            60: (
                                "wagtail.blocks.StructBlock",
                                [[("items", 59)]],
                                {"group": "Sections"},
                            ),
                            61: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small text above logos, e.g. 'Trusted by' or 'Certified by'.",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            62: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Logo image for a certification, association, or partner.",
                                    "required": True,
                                },
                            ),
                            63: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Descriptive alt text for the logo (accessibility).",
                                    "max_length": 255,
                                    "required": True,
                                },
                            ),
                            64: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Optional URL to link to (e.g. association website).",
                                    "required": False,
                                },
                            ),
                            65: (
                                "wagtail.blocks.StructBlock",
                                [[("logo", 62), ("alt_text", 63), ("url", 64)]],
                                {},
                            ),
                            66: (
                                "wagtail.blocks.ListBlock",
                                (65,),
                                {
                                    "help_text": "2-8 logo items for the trust strip.",
                                    "max_num": 8,
                                    "min_num": 2,
                                },
                            ),
                            67: (
                                "wagtail.blocks.StructBlock",
                                [[("eyebrow", 61), ("items", 66)]],
                                {"group": "Sections"},
                            ),
                            68: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small text above stats, e.g. 'By the Numbers'.",
                                    "max_length": 100,
                                    "required": False,
                                },
                            ),
                            69: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Optional introductory text below the eyebrow.",
                                    "required": False,
                                },
                            ),
                            70: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "The numeric value, e.g. '500+', '15', '98%'.",
                                    "max_length": 50,
                                    "required": True,
                                },
                            ),
                            71: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Short description, e.g. 'Projects Completed', 'Years Experience'.",
                                    "max_length": 100,
                                    "required": True,
                                },
                            ),
                            72: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional prefix before value, e.g. '>' or '£'.",
                                    "max_length": 10,
                                    "required": False,
                                },
                            ),
                            73: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional suffix after value, e.g. '+', 'yrs', '%'.",
                                    "max_length": 10,
                                    "required": False,
                                },
                            ),
                            74: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("value", 70),
                                        ("label", 71),
                                        ("prefix", 72),
                                        ("suffix", 73),
                                    ]
                                ],
                                {},
                            ),
                            75: (
                                "wagtail.blocks.ListBlock",
                                (74,),
                                {
                                    "help_text": "2-4 statistics to display.",
                                    "max_num": 4,
                                    "min_num": 2,
                                },
                            ),
                            76: (
                                "wagtail.blocks.StructBlock",
                                [[("eyebrow", 68), ("intro", 69), ("items", 75)]],
                                {"group": "Sections"},
                            ),
                            77: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Optional short label / kicker.",
                                    "required": False,
                                },
                            ),
                            78: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["italic", "bold"],
                                    "help_text": "Section heading.",
                                    "required": True,
                                },
                            ),
                            79: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "help_text": "Optional short supporting text.",
                                    "required": False,
                                },
                            ),
                            80: (
                                "wagtail.blocks.IntegerBlock",
                                (),
                                {
                                    "help_text": "Optional. If omitted, steps are auto-numbered.",
                                    "max_value": 20,
                                    "min_value": 1,
                                    "required": False,
                                },
                            ),
                            81: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "bold",
                                        "italic",
                                        "link",
                                        "ul",
                                        "ol",
                                        "document-link",
                                    ],
                                    "help_text": "Description of the step.",
                                    "required": False,
                                },
                            ),
                            82: (
                                "wagtail.blocks.StructBlock",
                                [[("number", 80), ("title", 51), ("description", 81)]],
                                {},
                            ),
                            83: (
                                "wagtail.blocks.ListBlock",
                                (82,),
                                {"max_num": 8, "min_num": 3},
                            ),
                            84: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 77),
                                        ("heading", 78),
                                        ("intro", 79),
                                        ("steps", 83),
                                    ]
                                ],
                                {"group": "Sections"},
                            ),
                            85: ("wagtail.blocks.CharBlock", (), {"required": False}),
                            86: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"features": ["italic", "bold"], "required": True},
                            ),
                            87: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic", "link"],
                                    "required": False,
                                },
                            ),
                            88: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ul",
                                        "ol",
                                        "document-link",
                                    ],
                                    "required": True,
                                },
                            ),
                            89: (
                                "wagtail.blocks.StructBlock",
                                [[("question", 51), ("answer", 88)]],
                                {},
                            ),
                            90: (
                                "wagtail.blocks.ListBlock",
                                (89,),
                                {"max_num": 20, "min_num": 1},
                            ),
                            91: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": True,
                                    "help_text": "If unchecked, opening one item closes others.",
                                    "required": False,
                                },
                            ),
                            92: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 85),
                                        ("heading", 86),
                                        ("intro", 87),
                                        ("items", 90),
                                        ("allow_multiple_open", 91),
                                    ]
                                ],
                                {"group": "Sections"},
                            ),
                            93: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "Emoji or text icon", "required": True},
                            ),
                            94: (
                                "wagtail.blocks.StructBlock",
                                [[("icon", 93), ("title", 51), ("description", 50)]],
                                {},
                            ),
                            95: ("wagtail.blocks.ListBlock", (94,), {}),
                            96: (
                                "wagtail.blocks.StructBlock",
                                [[("heading", 51), ("intro", 1), ("features", 95)]],
                                {"group": "Sections"},
                            ),
                            97: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small italic text above title",
                                    "required": False,
                                },
                            ),
                            98: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Background/Before image",
                                    "required": True,
                                },
                            ),
                            99: (
                                "wagtail.images.blocks.ImageChooserBlock",
                                (),
                                {
                                    "help_text": "Foreground/After image",
                                    "required": True,
                                },
                            ),
                            100: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("accent_text", 97),
                                        ("title", 51),
                                        ("description", 50),
                                        ("image_before", 98),
                                        ("image_after", 99),
                                    ]
                                ],
                                {"group": "Sections"},
                            ),
                            101: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small label above heading",
                                    "required": False,
                                },
                            ),
                            102: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["bold", "italic"],
                                    "help_text": "Main heading. Use italics for accent styling.",
                                    "required": True,
                                },
                            ),
                            103: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {"help_text": "Short lead text", "required": False},
                            ),
                            104: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Alt text for accessibility.",
                                    "required": True,
                                },
                            ),
                            105: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. Kensington, London",
                                    "required": False,
                                },
                            ),
                            106: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "e.g. Solar • Battery",
                                    "required": False,
                                },
                            ),
                            107: (
                                "wagtail.blocks.URLBlock",
                                (),
                                {
                                    "help_text": "Link to full project case study",
                                    "required": False,
                                },
                            ),
                            108: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 9),
                                        ("alt_text", 104),
                                        ("title", 51),
                                        ("location", 105),
                                        ("services", 106),
                                        ("link_url", 107),
                                    ]
                                ],
                                {},
                            ),
                            109: (
                                "wagtail.blocks.ListBlock",
                                (108,),
                                {"max_num": 12, "min_num": 1},
                            ),
                            110: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 101),
                                        ("heading", 102),
                                        ("intro", 103),
                                        ("items", 109),
                                    ]
                                ],
                                {"group": "Sections"},
                            ),
                            111: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [("left", "Left"), ("center", "Center")],
                                    "required": False,
                                },
                            ),
                            112: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"help_text": "e.g. Case Study", "required": False},
                            ),
                            113: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": ["italic", "bold"],
                                    "help_text": "Main title. Use italics for accent styling.",
                                    "required": True,
                                },
                            ),
                            114: (
                                "wagtail.blocks.StructBlock",
                                [[("align", 111), ("eyebrow", 112), ("heading", 113)]],
                                {"group": "Page Content"},
                            ),
                            115: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                        "hr",
                                    ],
                                    "required": True,
                                },
                            ),
                            116: (
                                "wagtail.blocks.StructBlock",
                                [[("align", 111), ("body", 115)]],
                                {"group": "Page Content"},
                            ),
                            117: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "help_text": "Short editorial quote (1-3 sentences).",
                                    "label": "Quote Text",
                                },
                            ),
                            118: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Role/description, e.g. Property Owner",
                                    "required": False,
                                },
                            ),
                            119: (
                                "wagtail.blocks.StructBlock",
                                [[("quote", 117), ("author", 85), ("role", 118)]],
                                {"group": "Page Content"},
                            ),
                            120: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"max_length": 255, "required": True},
                            ),
                            121: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Short caption under the image.",
                                    "required": False,
                                },
                            ),
                            122: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "default": False,
                                    "help_text": "Stretch to full-width container.",
                                    "required": False,
                                },
                            ),
                            123: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("image", 9),
                                        ("alt_text", 120),
                                        ("caption", 121),
                                        ("full_width", 122),
                                    ]
                                ],
                                {"group": "Page Content"},
                            ),
                            124: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("left", "Left"),
                                        ("center", "Center"),
                                        ("right", "Right"),
                                    ]
                                },
                            ),
                            125: ("wagtail.blocks.CharBlock", (), {}),
                            126: ("wagtail.blocks.URLBlock", (), {}),
                            127: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("primary", "Primary"),
                                        ("secondary", "Secondary"),
                                    ]
                                },
                            ),
                            128: (
                                "wagtail.blocks.StructBlock",
                                [[("label", 125), ("url", 126), ("style", 127)]],
                                {},
                            ),
                            129: (
                                "wagtail.blocks.ListBlock",
                                (128,),
                                {"max_num": 3, "min_num": 1},
                            ),
                            130: (
                                "wagtail.blocks.StructBlock",
                                [[("alignment", 124), ("buttons", 129)]],
                                {"group": "Page Content"},
                            ),
                            131: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("small", "Small (24px)"),
                                        ("medium", "Medium (40px)"),
                                        ("large", "Large (64px)"),
                                        ("xlarge", "X-Large (96px)"),
                                    ]
                                },
                            ),
                            132: (
                                "wagtail.blocks.StructBlock",
                                [[("size", 131)]],
                                {"group": "Page Content"},
                            ),
                            133: (
                                "wagtail.blocks.ChoiceBlock",
                                [],
                                {
                                    "choices": [
                                        ("muted", "Muted"),
                                        ("strong", "Strong"),
                                        ("accent", "Accent"),
                                    ]
                                },
                            ),
                            134: (
                                "wagtail.blocks.StructBlock",
                                [[("style", 133)]],
                                {"group": "Page Content"},
                            ),
                            135: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small label above heading (e.g. 'Enquiries')",
                                    "required": False,
                                },
                            ),
                            136: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"help_text": "Section heading", "required": True},
                            ),
                            137: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "help_text": "Optional introductory copy",
                                    "required": False,
                                },
                            ),
                            138: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "default": "Thanks, we'll be in touch shortly.",
                                    "required": False,
                                },
                            ),
                            139: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Send enquiry", "required": False},
                            ),
                            140: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 135),
                                        ("heading", 136),
                                        ("intro", 137),
                                        ("success_message", 138),
                                        ("submit_label", 139),
                                    ]
                                ],
                                {"group": "Forms"},
                            ),
                            141: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {
                                    "help_text": "Small label above heading (e.g. 'Project Application')",
                                    "required": False,
                                },
                            ),
                            142: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": True},
                            ),
                            143: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {"required": False},
                            ),
                            144: (
                                "wagtail.blocks.TextBlock",
                                (),
                                {
                                    "default": "Thanks, we'll prepare your quote.",
                                    "required": False,
                                },
                            ),
                            145: (
                                "wagtail.blocks.CharBlock",
                                (),
                                {"default": "Request a quote", "required": False},
                            ),
                            146: (
                                "wagtail.blocks.BooleanBlock",
                                (),
                                {
                                    "help_text": "Compact layout for sidebars/short sections.",
                                    "required": False,
                                },
                            ),
                            147: (
                                "wagtail.blocks.StructBlock",
                                [
                                    [
                                        ("eyebrow", 141),
                                        ("heading", 142),
                                        ("intro", 143),
                                        ("success_message", 144),
                                        ("submit_label", 145),
                                        ("show_compact_meta", 146),
                                    ]
                                ],
                                {"group": "Forms"},
                            ),
                            148: (
                                "wagtail.blocks.RichTextBlock",
                                (),
                                {
                                    "features": [
                                        "h2",
                                        "h3",
                                        "h4",
                                        "bold",
                                        "italic",
                                        "link",
                                        "ol",
                                        "ul",
                                    ],
                                    "help_text": "Add formatted text content. Use H2-H4 for headings, avoid H1.",
                                    "label": "Rich Text",
                                    "required": False,
                                },
                            ),
                        },
                        help_text="Add content blocks to build your homepage layout.",
                        null=True,
                    ),
                ),
                (
                    "og_image",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional. If blank, uses the page featured image (if present), otherwise the site default OG image.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home Page",
                "verbose_name_plural": "Home Pages",
            },
            bases=("wagtailcore.page", models.Model),
        ),
    ]
